#!/bin/bash

# This hook is executed after a new version of the app is deployed.

# Find the current running container and start the reminder scheduler job
CONTAINER_NAME=$(docker container ls --filter label=service=habit_tracker --filter label=destination= --format '{{.Names}}' | head -1)
if [ -n "$CONTAINER_NAME" ]; then
  docker exec $CONTAINER_NAME bin/rails scheduler:start
else
  echo "No running habit_tracker container found"
  exit 1
fi
